# Generated by Django 4.0 on 2021-12-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='event',
        ),
        migrations.AddField(
            model_name='notify',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.event'),
            preserve_default=False,
        ),
    ]
